version: "3.9"

services:
  ivcore:
    build: .
    network_mode: "host"
    container_name: ivcore_backend
    # ports:
    #   - "8000:8000" // removed for network_mode host
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok
    restart: unless-stopped

