version: "3.9"

services:
  ivcore:
    build: .
    container_name: ivcore_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok
    restart: unless-stopped

