DEVICE_ALLOWED_FIELDS = {
    "Sensor": {
        "name",
        "group_address_state",
        "value_type",
        "sync_state",
        "always_callback",
    },
    "Scene": {
        "name",
        "group_address",
        "scene_number",
    },
    "BinarySensor": {
        "name",
        "group_address_state",
        "invert",
        "sync_state",
        "ignore_internal_state",
        "reset_after",
        "context_timeout",
    },
    "Cover": {
        "name",
        "group_address_long",
        "group_address_short",
        "group_address_stop",
        "group_address_position",
        "group_address_position_state",
        "group_address_angle",
        "group_address_angle_state",
        "group_address_locked_state",
        "sync_state",
        "travel_time_down",
        "travel_time_up",
        "invert_updown",
        "invert_position",
        "invert_angle",
    },
    "Switch": {
        "name",
        "group_address",
        "group_address_state",
        "sync_state",
        "passive_group_addresses",
        "respond_to_read",
        "invert",
        "reset_after",
    },
    "Light": {
        "name",
        "sync_state",
        "group_address_color",
        "group_address_color_state",
        "group_address_rgbw",
        "group_address_rgbw_state",
        "group_address_hue",
        "group_address_hue_state",
        "group_address_saturation",
        "group_address_saturation_state",
        "group_address_xyy_color",
        "group_address_xyy_color_state",
        "group_address_tunable_white",
        "group_address_tunable_white_state",
        "group_address_color_temperature",
        "group_address_color_temperature_state",
        "group_address_switch_red",
        "group_address_switch_red_state",
        "group_address_brightness_red",
        "group_address_brightness_red_state",
        "group_address_switch_green",
        "group_address_switch_green_state",
        "group_address_brightness_green",
        "group_address_brightness_green_state",
        "group_address_switch_blue",
        "group_address_switch_blue_state",
        "group_address_brightness_blue",
        "group_address_brightness_blue_state",
        "group_address_switch_white",
        "group_address_switch_white_state",
        "group_address_brightness_white",
        "group_address_brightness_white_state",
        "color_temperature_type",
        "min_kelvin",
        "max_kelvin",
    },
    "Climate": {
        "name",
        "group_address_temperature",
        "group_address_target_temperature",
        "group_address_target_temperature_state",
        "group_address_setpoint_shift",
        "group_address_setpoint_shift_state",
        "setpoint_shift_mode",
        "setpoint_shift_max",
        "setpoint_shift_min",
        "temperature_step",
        "group_address_on_off",
        "group_address_on_off_state",
        "on_off_invert",
        "group_address_active_state",
        "group_address_command_value_state",
        "sync_state",
        "min_temp",
        "max_temp",
        "group_address_fan_speed",
        "group_address_fan_speed_state",
        "fan_speed_mode",
        "group_address_humidity_state",
        "group_address_swing",
        "group_address_swing_state",
        "group_address_horizontal_swing",
        "group_address_horizontal_swing_state",
    },
    "ClimateMode": {
        "name",
        "group_address_operation_mode",
        "group_address_operation_mode_state",
        "group_address_operation_mode_protection",
        "group_address_operation_mode_economy",
        "group_address_operation_mode_comfort",
        "group_address_operation_mode_standby",
        "group_address_controller_status",
        "group_address_controller_status_state",
        "group_address_controller_mode",
        "group_address_controller_mode_state",
        "group_address_heat_cool",
        "group_address_heat_cool_state",
        "sync_state",
        "operation_modes",
        "controller_modes",
    },
    "NumericValue": {
        "name",
        "group_address",
        "group_address_state",
        "sync_state",
        "value_type",
        "respond_to_read",
        "always_callback",
    },
    "RawValue": {
        "name",
        "group_address",
        "group_address_state",
        "sync_state",
        "payload_length",
        "respond_to_read",
        "always_callback",
    },
    "TimeDevice": {"name", "group_address", "localtime"},
    "DateDevice": {"name", "group_address", "localtime"},
    "DateTimeDevice": {"name", "group_address", "localtime"},
    "ExposeSensor": {
        "name",
        "group_address",
        "respond_to_read",
        "value_type",  # DPT, e.g. "temperature", "binary", etc.
        "cooldown",
    },
    "Fan": {
        "name",
        "group_address_speed",
        "group_address_speed_state",
        "group_address_oscillation",
        "group_address_oscillation_state",
        "group_address_switch",
        "group_address_switch_state",
        "sync_state",
        "max_step",
    },
    "Notification": {
        "name",
        "group_address",
        "group_address_state",
        "sync_state",
        "value_type",
        "respond_to_read",
    },
    "Weather": {
        "name",
        "group_address_temperature",
        "group_address_brightness_south",
        "group_address_brightness_north",
        "group_address_brightness_west",
        "group_address_brightness_east",
        "group_address_wind_speed",
        "group_address_wind_bearing",
        "group_address_rain_alarm",
        "group_address_frost_alarm",
        "group_address_wind_alarm",
        "group_address_day_night",
        "group_address_air_pressure",
        "group_address_humidity",
        "sync_state",
    },
}

__all__ = ["DEVICE_ALLOWED_FIELDS"]
